.libPaths(c("C:/Users/user/R/win-library/4.6", .libPaths()))
suppressPackageStartupMessages({ library(arrow); library(dplyr) })
df <- read_parquet("C:/Users/user/Documents/ProjetoRacismoPNAD/data/processed/features.parquet")
emp <- df[!is.na(df$empregado) & df$empregado == 1 & !is.na(df$renda_bruta) & df$renda_bruta > 0, ]
cat("Amostra empregados c/ renda:", nrow(emp), "\n")
cat("ocp_grupo_cbo - tipo:", class(emp$ocp_grupo_cbo), "\n")
cat("ocp_grupo_cbo - valores unicos (primeiros 20):\n")
print(sort(unique(emp$ocp_grupo_cbo))[1:20])
cat("ocp_grupo_cbo - tabela de frequencias:\n")
print(table(emp$ocp_grupo_cbo, useNA="always"))
cat("\neduc_ord - valores unicos:\n")
print(sort(unique(emp$educ_ord)))
cat("\nidade_c - head:\n")
print(head(emp$idade_c))